// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvNjXVZ2IMLVy5T3TVIyFdqkb8yFmFShc',
    appId: '1:505188938042:web:885a653c3d2b49cb3d2003',
    messagingSenderId: '505188938042',
    projectId: 'note-taking-app-64c85',
    authDomain: 'note-taking-app-64c85.firebaseapp.com',
    storageBucket: 'note-taking-app-64c85.appspot.com',
    measurementId: 'G-6B0FLHCKRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpaMjsW7mE8aGyna7B7TtSxAzfWqrsTEU',
    appId: '1:505188938042:android:cdba3afe926a20253d2003',
    messagingSenderId: '505188938042',
    projectId: 'note-taking-app-64c85',
    storageBucket: 'note-taking-app-64c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAOIY89M36vnTlrStZ20QEgAZq_Sr-X98',
    appId: '1:505188938042:ios:c0de3504884a4c2b3d2003',
    messagingSenderId: '505188938042',
    projectId: 'note-taking-app-64c85',
    storageBucket: 'note-taking-app-64c85.appspot.com',
    iosClientId: '505188938042-qgbbf41smkto3ecuk6d5f731lfl3fd1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteTakingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAOIY89M36vnTlrStZ20QEgAZq_Sr-X98',
    appId: '1:505188938042:ios:c0de3504884a4c2b3d2003',
    messagingSenderId: '505188938042',
    projectId: 'note-taking-app-64c85',
    storageBucket: 'note-taking-app-64c85.appspot.com',
    iosClientId: '505188938042-qgbbf41smkto3ecuk6d5f731lfl3fd1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteTakingApp',
  );
}
